# Generated by Django 4.2 on 2023-04-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_License_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('grad_university', models.CharField(max_length=100, null=True)),
                ('health_profession', models.CharField(max_length=200, null=True)),
                ('birth_date', models.DateTimeField(null=True)),
                ('year_of_graduation', models.DateTimeField(null=True)),
                ('grade_8th_ministry', models.ImageField(blank=True, null=True, upload_to='main/grade_8th_ministry/')),
                ('grade_10th_ministry', models.ImageField(blank=True, null=True, upload_to='main/grade_10th_ministry/')),
                ('grade_12th_ministry', models.ImageField(blank=True, null=True, upload_to='main/grade_12th_ministry/')),
                ('degree_certificate', models.ImageField(blank=True, null=True, upload_to='main/degree_certificate/')),
                ('recent_photo', models.ImageField(blank=True, null=True, upload_to='main/recent_photo/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='regain_lost_license',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('health_profession', models.CharField(max_length=200, null=True)),
                ('birth_date', models.DateTimeField(null=True)),
                ('date_issued', models.DateTimeField(null=True)),
                ('recent_photo', models.ImageField(blank=True, null=True, upload_to='regain/recent_photo/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='renew_lost_license',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('health_profession', models.CharField(max_length=200, null=True)),
                ('grad_university', models.CharField(max_length=200, null=True)),
                ('birth_date', models.DateTimeField(null=True)),
                ('date_issued', models.DateTimeField(null=True)),
                ('old_license', models.ImageField(blank=True, null=True, upload_to='renew/old_license/')),
                ('recent_photo', models.ImageField(blank=True, null=True, upload_to='renew/recent_photo/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
