# Generated by Django 4.2 on 2023-05-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MLAR_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('grad_university', models.CharField(max_length=100, null=True)),
                ('birth_date', models.DateTimeField(null=True)),
                ('year_of_graduation', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=500, null=True)),
                ('employee_position', models.CharField(max_length=500, null=True)),
                ('date_issued', models.DateTimeField(auto_now_add=True, null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.application')),
            ],
        ),
        migrations.CreateModel(
            name='First_License_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=200, null=True)),
                ('health_profession', models.CharField(max_length=200, null=True)),
                ('grade_8th_ministry', models.ImageField(blank=True, null=True, upload_to='main/grade_8th_ministry/')),
                ('grade_10th_ministry', models.ImageField(blank=True, null=True, upload_to='main/grade_10th_ministry/')),
                ('grade_12th_ministry', models.ImageField(blank=True, null=True, upload_to='main/grade_12th_ministry/')),
                ('degree_certificate', models.ImageField(blank=True, null=True, upload_to='main/degree_certificate/')),
                ('recent_photo', models.ImageField(blank=True, null=True, upload_to='main/recent_photo/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Renew_last_license',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=200, null=True)),
                ('old_license', models.ImageField(blank=True, null=True, upload_to='renew/old_license/')),
                ('recent_photo', models.ImageField(blank=True, null=True, upload_to='renew/recent_photo/')),
                ('date_issued', models.DateTimeField(auto_now_add=True, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.applicant')),
                ('first_license', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.first_license_application')),
            ],
        ),
        migrations.CreateModel(
            name='Validate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_status', models.CharField(max_length=500, null=True)),
                ('declination_reason', models.CharField(max_length=500, null=True)),
                ('date_issued', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ManyToManyField(to='MLAR_app.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='New_License_Application',
        ),
        migrations.DeleteModel(
            name='renew_lost_license',
        ),
        migrations.RemoveField(
            model_name='regain_lost_license',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='regain_lost_license',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='regain_lost_license',
            name='gender',
        ),
        migrations.AlterField(
            model_name='regain_lost_license',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='first_license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.first_license_application'),
        ),
        migrations.AddField(
            model_name='application',
            name='lost_license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.renew_last_license'),
        ),
        migrations.AddField(
            model_name='application',
            name='renew_license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.regain_lost_license'),
        ),
        migrations.AddField(
            model_name='regain_lost_license',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.applicant'),
        ),
        migrations.AddField(
            model_name='regain_lost_license',
            name='first_license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.first_license_application'),
        ),
    ]
