# Generated by Django 4.2 on 2023-05-05 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MLAR_app', '0002_applicant_application_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.applicant'),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.first_license_application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='lost_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.renew_last_license'),
        ),
        migrations.AlterField(
            model_name='application',
            name='renew_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MLAR_app.regain_lost_license'),
        ),
    ]
