# Generated by Django 4.2 on 2023-05-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLAR_app', '0004_remove_employee_application_validate_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regain_lost_license',
            name='email',
        ),
        migrations.RemoveField(
            model_name='regain_lost_license',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='regain_lost_license',
            name='health_profession',
        ),
        migrations.RemoveField(
            model_name='regain_lost_license',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='regain_lost_license',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='regain_lost_license',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='regain_lost_license',
            name='serial_no',
        ),
        migrations.AlterField(
            model_name='validate',
            name='declination_reason',
            field=models.CharField(choices=[('Forgery', 'Forgery'), ('Low Quality Documents', 'Low Quality Documents'), ('Invalid Credentials', 'Invalid Credentials')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='validate',
            name='validation_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined')], max_length=500, null=True),
        ),
    ]
