# Generated by Django 4.2 on 2023-05-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLAR_app', '0005_remove_regain_lost_license_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='first_license_application',
            old_name='date_created',
            new_name='date_issued',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='year_of_graduation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
