# Generated by Django 4.2 on 2023-05-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLAR_app', '0008_alter_first_license_application_id_serial_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regain_lost_license',
            name='id_serial_no',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
