# Generated by Django 4.2 on 2023-05-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLAR_app', '0010_first_license_application_declination_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first_license_application',
            name='declination_reason',
            field=models.CharField(choices=[('Forgery', 'Forgery'), ('Low Quality Documents', 'Low Quality Documents'), ('Invalid Credentials', 'Invalid Credentials')], default='NOT DECLINED', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='first_license_application',
            name='validation_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined')], default='NOT VERIFIED', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='regain_lost_license',
            name='declination_reason',
            field=models.CharField(choices=[('Forgery', 'Forgery'), ('Low Quality Documents', 'Low Quality Documents'), ('Invalid Credentials', 'Invalid Credentials')], default='NOT DECLINED', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='regain_lost_license',
            name='validation_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined')], default='NOT VERIFIED', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='renew_last_license',
            name='declination_reason',
            field=models.CharField(choices=[('Forgery', 'Forgery'), ('Low Quality Documents', 'Low Quality Documents'), ('Invalid Credentials', 'Invalid Credentials')], default='NOT DECLINED', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='renew_last_license',
            name='validation_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined')], default='NOT VERIFIED', max_length=500, null=True),
        ),
    ]
